version: '3.8'

services:
  facematch:
    build: .
    container_name: facematch
    ports:
      - 8000:8000
    volumes:
      - ./config:/app/config
      - ./images:/app/images
      - ./results:/app/results
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py