openapi: 3.0.0
paths:
  /:
    get:
      summary: endpoint to check if the API is working
      responses:
        '200':
          description: API is working
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: API is Online!
                  status:
                    type: string
                    example: ONLINE
  /verify-faces:
    post:
      summary: endpoint to verify faces using external url
      description: This endpoint will verify faces from a photo and doc using external url.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiArgsModel'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaceMatchResponse'
      security:
        - apiKey: []
  /verify-faces/image:
    post:
      summary: endpoint to verify faces uploading images
      description: This endpoint will verify faces from a photo and doc using image uploaded.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FacePictureFileDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaceMatchResponse'
      security:
        - apiKey: []

info:
  title: FaceMatch API Specification
  description: ''
  version: '1.0'
  contact: {}
tags: []
servers:
  - url: /
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    FacePictureFileDto:
      type: object
      properties:
        face:
          type: string
          format: binary
          description: Single file
        document:
          type: string
          format: binary
          description: Single file
      required:
        - face
        - document
    FaceMatchResponse:
      type: object
      properties:
        verified:
          type: boolean
          example: false
        similarity_distance:
          type: number
          example: 0.8441984834065039
        similarity_threshold:
          type: number
          example: 0.68
        fake_face:
          type: boolean
          example: null
        fake_score:
          type: number
          example: null
        face_attributes:
          type: object
          example: null
    ApiArgsModel:
      type: object
      properties:
        face_img:
          type: string
          description: Face image
          example: https://i.imgur.com/w4e4h4b.jpg
        doc_img:
          type: string
          description: Document image
          example: https://i.imgur.com/w4e4h4b.jpg
        detect_fraud:
          type: boolean
          description: Detect fraud
        detect_face_attributes:
          type: array
          items:
            type: string
            enum:
              - emotion
              - age
              - gender
              - race
          description: Detect face attributes
        remove_image:
          type: boolean
          description: Remove images after verification
      required:
        - face_img
        - doc_img